### PR TITLE
CSHARP-2873: Add google analytics support to all driver docs

### PR DESCRIPTION
**Pull request by MikalaiMazurenka**
https://jira.mongodb.org/browse/CSHARP-2873

Note: Nathan Leniz (mentioned as contact person on original ticket [DRIVERS-784](https://jira.mongodb.org/browse/DRIVERS-784)) said that changes look correct.

### CODE REVIEW

**Comment by MikalaiMazurenka** [comment]
There is a chance that more changes should be added. I will update when PR is ready for review.

**Comment by MikalaiMazurenka** [comment]
False call. Everything is correct.
Ready for review!

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Review by vincentkam — APPROVED** [review]
A very high-level LGTM :)

**Pull request closed without merging**
