### PR TITLE
CSHARP-2846: Remove 'latest' from evergreen config for v2.9.x branch

### PR DESCRIPTION
**Pull request by MikalaiMazurenka**
Evergreen: https://evergreen.mongodb.com/version/5ddfc3772fbabe1e1bc059a9

### CODE REVIEW

**Review by jyemin — APPROVED** [review]
LGTM!

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Review by rstam — APPROVED** [review]
The change itself looks fine.

But I don't understand WHY we are making this change. Seems like we should test 2.9.x against latest.

**Comment by jyemin** [comment]
We make this change because often the server will make some change in latest that will break our test suite, and we don't want to have to backport any test suite changes to release branches.  We don't make guarantees of compatibility of release branches with subsequent server releases, so it's fine not to get against them.

**Review by vincentkam — APPROVED** [review]
LGTM! 😸

**Pull request closed without merging**
