### PR TITLE
CSHARP-3066: Improve MongoX509Credential API

### PR DESCRIPTION
**Pull request by MikalaiMazurenka**
https://jira.mongodb.org/browse/CSHARP-3066
Evergreen:  https://evergreen.mongodb.com/version/5ea9e09b3627e0251caf77f0

### CODE REVIEW

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Comment by jyemin** [comment]
Seems like this could use an integration test, perhaps based on the work for https://jira.mongodb.org/browse/CSHARP-3031.

**Review by vincentkam — APPROVED** [review]
LGTM! (●'◡'●) If you decide that waiting for an integration test is worth it, then we could wait till 3031 is resolved and then rebase and tweak the existing test to use the new API when the test detects its on the appropriate server version.

**Comment by MikalaiMazurenka** [comment]
I will wait for 3031 to be pushed in master and will utilize the integration test from there.

**Review by rstam — APPROVED** [review]
LGTM

**Comment by MikalaiMazurenka** [comment]
Updated the PR to account for https://jira.mongodb.org/browse/CSHARP-3031.
Ready for review!

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Review by rstam — APPROVED** [review]
LGTM

**Pull request closed without merging**
