### PR TITLE
CSHARP-2880: Change uri_options/auth-options spec test to enable conditional tests

### PR DESCRIPTION
**Pull request by MikalaiMazurenka**
https://jira.mongodb.org/browse/CSHARP-2880
https://evergreen.mongodb.com/version/5eb0268a7742ae2d72cae0fc

### CODE REVIEW

**Comment by MikalaiMazurenka** [comment]
Ready for review!

**Review by DmitryLukyanov — APPROVED** [review]
Waiting for EG and then LGTM

**Comment by rstam** [comment]
No action needed on this code review, but in the future it will probably be better to rebase your branch on the newest commit in master before creating the pull request.

**Review by rstam — CHANGES_REQUESTED** [review]
Code changes look fine. Can you check the failed tasks in Evergreen and report back here whether they are related or not to this pull request?

**Review by vincentkam — APPROVED** [review]
LGTM!  (●'◡'●) 😸

**Comment by MikalaiMazurenka** [comment]
Rebased onto master. Evergreen looks greener now, but latest still fails.
(added tests are not failing)

**Review by rstam — APPROVED** [review]
LGTM

**Pull request closed without merging**
